branches:
  only:
    - master

notifications:
  slack: 
    rooms:
      secure: "a+W3yrcab0GVRhmIUXsdV1KpNxX6Qe7LnX6vq4Ou4mCSSaBln0mL0y4Gs1GSPdiq5PWhYrcIgAsESQiCDbi5JoW//GyEovZvY+WDgnhrskoOLFgWqxhT1yInDkLRfkQZAdL/5uWOBDSr1d+2/1qqeciWMebQQZoEezeKoKwPtdQ="
  
language: java
sudo: false
cache:
  directories:
  - $HOME/.gradle

script: "./gradle clean check test htmlunit"

jdk:
  - oraclejdk8

after_success:
- ./gradle jacocoTestReport coveralls